### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by ilyakooo0** [ilyakooo0/podphoenix#23]
I no longer use Ubuntu Touch. This makes it hard for me to maintain podphoenix.

**Comment by maciek134** [comment]
Happy to help. I already maintain [WaydroidHelper](https://github.com/Aarontheissueguy/WaydroidHelper) and [LogViewer](https://github.com/maciek134/LogViewer) and started looking into podphoenix's code recently to help with a couple of bugs I encountered.

**Comment by ilyakooo0** [comment]
@maciek134 Could you delete your fork so that I can transfer the repo?

**Comment by ilyakooo0** [comment]
Done

**Comment by ilyakooo0** [comment]
@maciek134 what email is your open-store account tied to?

**Comment by maciek134** [comment]
Deleted my fork, I don't think I have an e-mail address associated with my OpenStore account since I login with SSO, my user id is `61d496d9d0962deb926ede05`

**Comment by maciek134** [comment]
The email associated with the GitLab account I use for SSO is `me@klh.io`

**Comment by ilyakooo0** [comment]
@maciek134 I initiated the repo transfer

I think the transition of ownership is now complete
